# Requires these plugin packages at runtime:
#   std_msgs_robofleet
#   geometry_msgs_robofleet
#   std_srvs_robofleet

# """
# SEE THE FOLLOWING WIKI PAGE WITH HELP FOR TOPIC NAMES AND TYPES
# AugRE Wiki: https://wikis.utexas.edu/pages/viewpage.action?pageId=394401756
# """

params:
  # leave blank to run in Direct Mode
  # IP Address for local NRG robofleet_server ws://192.168.11.11:8080
  host_url: "ws://192.168.11.11:8080"
  #host_url: "ws://192.168.0.10:8080"

  # Do not worry about this. Talk to Blake for explanations
  wait_for_pongs: true
  max_queue_before_waiting: 5

  # uncomment to run in Direct Mode
  #direct_mode_port: 8080
  #direct_mode_bytes_per_sec: 2048000

  # Verbosity 0 - MINIMAL
  # Verbosity 1 - CONFIG_ONLY
  # Verbosity 2 - ALL
  verbosity: 1

  # you may need more threads to handle a large amount of traffic
  spin_threads: 1

publishers: [ # these are the topics to publish to the robofleet server
  {
    client_topic: "/server/surface_repair/lasso/pc_points_tagged",
    rbf_topic: "/server/surface_repair/lasso/pc_points_tagged",
    type: "std_msgs/UInt8MultiArray"
  },
  {
    client_topic: "/server/surface_repair/highlight/pc_points_tagged",
    rbf_topic: "/server/surface_repair/highlight/pc_points_tagged",
    type: "std_msgs/UInt8MultiArray"
  }
]

subscribers: [ # these are the topics to subscribe to on the robofleet server
  {
    client_topic: "/junk/empty",
    rbf_topic: "/junk/empty",
    type: "std_msgs/Empty"
  },
  {
    client_topic: "/vaultbot/goal_pose",
    rbf_topic: "/vaultbot/goal_pose",
    type: "geometry_msgs/PoseStamped",
    no_drop: true
  },
  {
    client_topic: "/junk/compressed_image",
    rbf_topic: "/junk/compressed_image",
    type: "sensor_msgs/CompressedImage",
    rate_limit: 100.0
  },
  {
    client_topic: "/hololens/surface_repair/user_feedback",
    rbf_topic: "/hololens/surface_repair/user_feedback",
    type: "std_msgs/UInt8"
  },
  {
    client_topic: "/hololens/surface_repair/bounding_objects",
    rbf_topic: "/hololens/surface_repair/bounding_objects",
    type: "augre_msgs/BoundingObject3DArray"
  },
  {
    client_topic: "/vaultbot/detection",
    rbf_topic: "/vaultbot/detection",
    type: "augre_msgs/DetectedItem",
    no_drop: true,
    queue: 10
  },
  {
    client_topic: "/vaultbot/surface_repair/surface_points",
    rbf_topic: "/vaultbot/surface_repair/surface_points",
    type: "sensor_msgs/PointCloud2",
    no_drop: true,
    queue: 10
  },
  {
    client_topic: "/vaultbot/surface_repair/virtual_fixtures",
    rbf_topic: "/vaultbot/surface_repair/virtual_fixtures",
    type: "sensor_msgs/PointCloud2",
    no_drop: true,
    queue: 10
  },
  {
    client_topic: "/hololens/surface_repair/lasso/points",
    rbf_topic: "/hololens/surface_repair/lasso/points",
    type: "geometry_msgs/PolygonStamped"
  },
  {
    client_topic: "/hololens/surface_repair/highlight/points",
    rbf_topic: "/hololens/surface_repair/highlight/points",
    type: "geometry_msgs/PolygonStamped"
  }
]
